### ISSUE TITLE
issues with formatting content in Quill

### ISSUE THREAD

**Issue by knkiers** [quantum-bits/galilee-webapp#100]
When logged in as an admin, and adding content (under Daily Readings), there are 2 issues:
1. Click on Add Practice -- the Quill text box doesn't show `boldface` properly within the text box (although the boldface property *does* get added into the html that gets generated).
2. Once the content is actually created, "open" the box (click on the "+") -- now bulleted lists and enumerated lists are not displayed properly, although boldfaced items are.

On the UI side, when looking at the practice that is created, enumerated lists work, as does boldface, but not bulleted lists.

**Comment by tparr** [comment]
@JudahDoupe  Are you working on this? If so, could you assign yourself to it?

**Comment by stephenenzor** [comment]
@tparr asked Judah, he said no

**Comment by TaylorDunlop95** [comment]
On this issue -I cannot see any steps regarding the daily practices at all.... Any thoughts?
