### ISSUE TITLE
give a stronger visual cue that a day does not have readings associated with it

### ISSUE THREAD

**Issue by knkiers** [quantum-bits/galilee-webapp#102]
On `end-user/readings`, a given tab on the date-nav is disabled if there are no readings for that day (the slider won't go there, and there is also a tool-tip that says 'no readings'), but there should be a stronger-visual cue as well.  Maybe the text could be light grey instead of light blue, or something.

**Comment by FreyjaShelton** [comment]
I decreased the amount of time it takes for the "no readings" message to come up. Ill work on the text color now
