### ISSUE TITLE
add a date-picker for admins to go directly to a particular date

### ISSUE THREAD

**Issue by knkiers** [quantum-bits/galilee-webapp#103]
<img width="639" alt="screen shot 2017-04-06 at 10 55 16 pm" src="https://cloud.githubusercontent.com/assets/16855838/24783850/d448fbf8-1b1c-11e7-8d79-f50b5367a50c.png">

Maybe have an icon to the right of the `>` button in the above image (only for admin users); when they click on it, they get the `date-picker` from here: http://materializecss.com/forms.html .

The date-picker seems to be tied to an `input` tag; I'm not sure if it's possible to launch it programmatically.

This might also be helpful: https://github.com/InfomediaLtd/angular2-materialize/tree/master/app/components

**Comment by tparr** [comment]
@knkiers I have two different styles currently. Any suggestions?
![issue 103 primary](https://cloud.githubusercontent.com/assets/12851750/25451191/59c9058a-2a8f-11e7-948a-a77e6fa9ce6d.png)
![issue 103 - secondary](https://cloud.githubusercontent.com/assets/12851750/25451192/59c98cee-2a8f-11e7-8184-0d56788157a6.png)

**Comment by knkiers** [comment]
I like the second one (with the cyan as a secondary colour).  Looks good!
