### ISSUE TITLE
date-nav should show up for a non-logged-in user

### ISSUE THREAD

**Issue by knkiers** [quantum-bits/galilee-webapp#109]
date nav appears after a user logs in, and stays after the user logs out, but if the user comes to the page without being logged in, it is not there

**Comment by TaylorDunlop95** [comment]
It seems to be the case that the only time that a non-logged in user can see is -immediately- after they log off. If the page is refreshed at all, then the date nav will disappear as expected...
Is there anyway that we could just "force" a refresh of the page? Or is that a little hacky?

**Comment by TaylorDunlop95** [comment]
"Everyone can see the bar, but only two weeks out. Only admin's can see all the dates" - Dr. Nurk

**Comment by TaylorDunlop95** [comment]
We got it
