### ISSUE TITLE
times in journal entries (e.g., 3 hrs ago) are sometimes below the edge of the collection item

### ISSUE THREAD

**Issue by knkiers** [quantum-bits/galilee-webapp#14]

**Comment by stephenenzor** [comment]
@knkiers Are you able to recreate this issue? The journal entry times I can see are displayed as being from at least a month ago and I've gone ahead and made a new "test" journal entry, but haven't been able to recreate this issue in mobile or desktop scenarios.

**Comment by knkiers** [comment]
I think I may have fixed this at some point and not removed the issue.
