### ISSUE TITLE
add endpoints to delete, add, update practices and steps

### ISSUE THREAD

**Issue by knkiers** [quantum-bits/galilee-webapp#20]
- add methods to reading-service that can be called from within update-readings-list
- the following methods are more or less ready to go within update-readings-list (as in, they are ready to hit methods in the service):

- onDeleteReading()
- onDeleteApplication()
- onAddPractice()
- onAddReading()

**Comment by nurkkala** [comment]
Reading and practice endpoints and service methods are in place. Need to be wired up to UI.

Still working on application/step endpoints.

**Comment by knkiers** [comment]
all wired up now
