### ISSUE TITLE
questions are returned from server in seq order

### ISSUE THREAD

**Issue by knkiers** [quantum-bits/galilee-webapp#25]
I think the questions might be returned in chronological order instead of sequence order.

**Comment by nurkkala** [comment]
There is an ORDER BY clause in the query that sorts by the sequence number. How can I reproduce the problem?

**Comment by knkiers** [comment]
Here's a quick demo: [https://screencast.com/t/OS82fipNCN](url)

**Comment by infinitesteps** [comment]
Is this still an issue? I don't see an "add question" button on the current interface.

**Comment by knkiers** [comment]
This is obsolete -- we used to have separate "questions", but this functionality has now been integrated into the practices themselves.
