### ISSUE TITLE
right half of copyright info line in footer disappears on a small device

### ISSUE THREAD

**Issue by knkiers** [quantum-bits/galilee-webapp#49]
probably need to put less content here...?  The link seems important, though.

**Comment by stephenenzor** [comment]
I'll look into solving the issue either by reducing the content here as you suggest or finding another solution. Preferably, there will be a way to get the footer to automatically resize or wrap itself so there's no cut off.

**Comment by knkiers** [comment]
ideally it would line wrap, but the footer in `materialize css` might only be able to one line high.  Not sure....

**Comment by knkiers** [comment]
content is not quite centered vertically....

**Comment by knkiers** [comment]
fixed using some css
