### ISSUE TITLE
In dropdown to select readings, gray out the current one

### ISSUE THREAD

**Issue by nurkkala** [quantum-bits/galilee-webapp#67]

**Comment by tparr** [comment]
@nurkkala 
Just wanted to confirm what you wanted here. The current option that is being hovered over is also grayed out. In the second image, the second version is selected and the top option has the mouse over it. Are you ok with the way this currently looks? I was thinking more of a disabled look or even hiding the current version selected from the dropdown.
![quantumbits issue 67](https://cloud.githubusercontent.com/assets/12851750/24487912/36f61a48-14e1-11e7-8eb2-8f58d92bee7a.png)
![quantum bits issue 67 new](https://cloud.githubusercontent.com/assets/12851750/24487913/36fe1cfc-14e1-11e7-8dfe-182eeedbb346.png)

**Comment by tparr** [comment]
Just to help you see what the option for hiding elements looks like.

![quantum bits issue 67 hidden](https://cloud.githubusercontent.com/assets/12851750/24488329/1549ee94-14e4-11e7-978c-2719ac9f6689.png)

**Comment by knkiers** [comment]
My personal preference would be to show all of the options in the dropdown, but maybe to have a disabled look or something for the current passage.  The middle image, where two passages are grey, seems a bit confusing to me.

**Comment by tparr** [comment]
@knkiers Got it. I'll apply some styling to make it absolutely clear that it is disabled.
