### ISSUE TITLE
Deal with unexpected cookies

### ISSUE THREAD

**Issue by nurkkala** [quantum-bits/galilee-webapp#80]
When the server receives a request with cookies in it (which we don't create or expect), it freaks out. It shouldn't.

**Comment by nurkkala** [comment]
According to the Hapi documentation, the default action when failing to parse a cookie is to "return a Bad Request (400) error response." There are also `log` and `ignore` actions, which seem like alternatives we should explore. However, so far, I can't replicate the error. I'm not sure we should move from the default Hapi behavior without a test case.

**Comment by knkiers** [comment]
That makes sense.  Not sure how to proceed on this, then....

**Comment by nurkkala** [comment]
We have only seen this with Susan's machine and have not been able to replicate the problem. Closing for now.
