### ISSUE TITLE
add static pages describing the benefits of creating an account, and how to use Journal and Forum features

### ISSUE THREAD

**Issue by knkiers** [quantum-bits/galilee-webapp#90]
The top nav bar should get a help button that is just a "?" icon, way off to the right

The entries could be:
- Why log in?
- How to use the forum
- How to use the Journal

**Comment by TaylorDunlop95** [comment]
Note to self: make it like the "About Galilee" card page

**Comment by TaylorDunlop95** [comment]
I have all of the components made and routed up. I can't set the "help button" in the desired position, so it is simply there with the others on the nav-bar for the moment.

Each of the components are designed like the static info page at present - cards with some very simple placeholder text and the question posed as the card title.

**Comment by TaylorDunlop95** [comment]
all on the branch feature/static-help-pages

**Comment by TaylorDunlop95** [comment]
Added content from Dr. Collins! 
Probably needs some polish, but everything is there.
